In [30]:
from selenium import webdriver
from time import sleep as sl
import pandas as pd
import pyautogui as py

df = pd.read_excel('projeto_bi_2.xlsx')
display(df)

     AÇÕES
0    RPAD6
1    RPMG3
2    RRRP3
3    RSID3
4    RSUL3
..     ...
106  WHRL3
107  WHRL4
108  WLMM3
109  WLMM4
110  YDUQ3

[111 rows x 1 columns]

In [31]:
navegador = webdriver.Chrome()
navegador.get('https://www.google.com')
link = 'https://statusinvest.com.br/'
navegador.get(link)
print(link)

py.keyDown('win')
py.press('up')
py.keyUp('win')
cot_atual2 = []
preco_min2 = []
preco_max2 = []
div_yield2 = []
liq_diaria2 = []
p_vp2 = []
cagr2 = []
patr_liq2 = []
caixa2 = []
lucro2 = []
for c in df['AÇÕES']:
    #print(c)
    
    navegador.find_element('xpath', '//*[@id="main-nav-nav"]/div/div/div/ul/li[2]/a/i').click()
    navegador.find_element('xpath', '//*[@id="main-search"]/div[1]/span[1]/input[2]').send_keys(c)
    sl(3)
    navegador.find_element('xpath', '//*[@id="main-search"]/div[2]/div/div/a').click()
    sl(1.5)
    cot_atual = navegador.find_element('xpath', '//*[@id="main-2"]/div[2]/div/div[1]/div/div[1]/div/div[1]/strong').text
    #print('COTAÇÃO ATUAL')
    #print(cot_atual)
    cot_atual2.append(cot_atual)
    #print()
    
    preco_min = navegador.find_element('xpath', '//*[@id="main-2"]/div[2]/div/div[1]/div/div[2]/div/div[1]/strong').text
    #print('PREÇO MÍNIMO')
    #print(preco_min)
    preco_min2.append(preco_min)
    #print()
    
    preco_max = navegador.find_element('xpath', '//*[@id="main-2"]/div[2]/div/div[1]/div/div[3]/div/div[1]/strong').text
    #print('PREÇO MÁXIMO')
    #print(preco_max)
    preco_max2.append(preco_max)
    #print()
    
    div_yield = navegador.find_element('xpath', '//*[@id="main-2"]/div[2]/div/div[1]/div/div[4]/div/div[1]/strong').text
    #print('DIVIDEND YIELD')
    #print(div_yield)
    div_yield2.append(div_yield)
    #print()
    
    py.scroll(-1200)
    sl(0.8)
    liq_diaria = navegador.find_element('xpath', '//*[@id="main-2"]/div[2]/div/div[5]/div/div/div[3]/div/div/div/strong').text
    # o .text pega o que não está dentro de uma variável "value"
    #print('liquidez diária')
    #print(liq_diaria)
    liq_diaria2.append(liq_diaria)
    #print()
    
    py.scroll(-700)
    p_vp = navegador.find_element('xpath', '//*[@id="indicators-section"]/div[2]/div/div[1]/div/div[4]/div/div/strong').text
    #print('p/vp')
    #print(p_vp)
    p_vp2.append(p_vp)
    #print()
    
    cagr = navegador.find_element('xpath', '//*[@id="indicators-section"]/div[2]/div/div[5]/div/div[2]/div/div/strong').text
    cagr2.append(cagr)
    
    navegador.find_element('xpath', '//*[@id="main-2"]/div[1]/div/div/ul/li[2]/a').click()
    sl(1)
    patr_liq = navegador.find_element('xpath', '//*[@id="company-section"]/div[1]/div/div[2]/div[1]/div/div/strong').text
    #print('PATRIMÔNIO LÍQUIDO')
    #print(patr_liq)
    patr_liq2.append(patr_liq)
    #print()
    
    navegador.find_element('xpath', '//*[@id="main-2"]/div[1]/div/div/ul/li[3]/a').click()
    sl(1)
    py.scroll(-1000)
    sl(2)
    caixa = navegador.find_element('xpath', '//*[@id="contabil-section"]/div[1]/div/div[3]/div[1]/div[1]/table/tbody/tr[1]/td[2]/span').text
    #print('CAIXA LÍQUIDO')
    #print(caixa)
    caixa2.append(caixa)
    #print()
    
    lucro = navegador.find_element('xpath', '//*[@id="contabil-section"]/div[1]/div/div[3]/div[1]/div[1]/table/tbody/tr[3]/td[2]/span').text
    #print('LUCRO LÍQUIDO')
    #print(lucro)
    lucro2.append(lucro)
    #print()

https://statusinvest.com.br/

In [ ]:
#df = pd.DataFrame(df[''])

In [32]:
df = pd.DataFrame(zip(cot_atual2, preco_min2, preco_max2, div_yield2, liq_diaria2, p_vp2, cagr2, patr_liq2, caixa2, lucro2), columns=['COTAÇÃO ATUAL', 'PREÇO MÍNIMO', 'PREÇO MÁXIMO', 'DIVIDEND YIELD', 'LIQUIDEZ DIÁRIA', 'P/VP', 'CAGR LUCRO', 'PATRIMÔNIO LÍQUIDO', 'CAIXA', 'LUCRO'])
display(df)

,COTAÇÃO ATUAL,PREÇO MÍNIMO,PREÇO MÁXIMO,DIVIDEND YIELD,LIQUIDEZ DIÁRIA,P/VP,CAGR LUCRO,PATRIMÔNIO LÍQUIDO,CAIXA,LUCRO
0,"6,49","4,16","6,90","0,01","83.934,33","0,52","8,81%",1.066.751.000,"3,30 M","66,39 M"
1,"1,60","1,52","2,91",-,"18.924,90","-0,03",-%,-3.855.234.000,"40,71 M","-361,85 M"
2,"32,87","27,18","51,31",-,"270.141.147,48","1,54",-%,4.341.275.000,"90,31 M","127,72 M"
3,"2,96","1,81","6,49",-,"158.971,23","-0,05",-%,-1.108.463.000,"29,51 M","-451,06 M"
4,"0,00",-,-,-,-,"0,00","12,74%",143.057.000,"50,77 M","92,58 M"
...,...,...,...,...,...,...,...,...,...,...
106,"4,44","4,36","5,72","4,21","8.228,37","3,06","-0,89%",2.181.353.000,"614,48 M","553,03 M"
107,"4,46","4,33","5,79","4,61","41.941,71","3,07","-0,89%",2.181.353.000,"614,48 M","553,03 M"
108,"22,00","19,23","29,24","5,79","4.400,00","1,29",-%,622.409.000,"-144,31 M","117,27 M"
109,"21,40","15,32","32,23","3,82","27.594,52","1,25",-%,622.409.000,"-144,31 M","117,27 M"
110,"8,16","6,55","18,06","1,55","33.912.236,35","0,85",-%,2.960.059.000,"716,87 M","-87,21 M"

In [33]:
df.to_excel('investimento_selenium_4.xlsx')